### ISSUE TITLE
Feature request - Support session ID in the header instead of a cookie

### ISSUE THREAD

**Issue by JCapriotti** [ibejohn818/flask-dynamodb-sessions#2]
This is a slight edge case but cookies are difficult for me to work with, so need to send the session ID back and forth in a normal header.

I haven't worked on this yet but intend to start so will submit a PR when finished.

**Comment by ibejohn818** [comment]
I've merged your PR and pushed the tag to PyPi.
I'm going to finish the test coverage and push another tag to pypi, no changes to the interface/module as I'm currently using this in production for a few apps. 
Thanks for the PR!
