### ISSUE TITLE
Strongly consistent reads

### ISSUE THREAD

**Issue by JCapriotti** [ibejohn818/flask-dynamodb-sessions#4]
Is there any reason to *not* do a strongly consistent read from DynamoDB? I'm only just starting to use this library, but I fear I will have a stale read sooner rather than later. 

It is a very simple change I can make; just curious if there are reasons to not do it? Probably should make it configurable since different users will have different preferences and scaling needs.

**Comment by JCapriotti** [comment]
I added this to #3

**Comment by ibejohn818** [comment]
Thanks for the PR. 
https://github.com/ibejohn818/flask-dynamodb-sessions/issues/2
